DELIMITER $$

CREATE PROCEDURE getArtByPriceRanges()

BEGIN


    START TRANSACTION;

    (SELECT * FROM art WHERE price BETWEEN 0 AND 100000 ORDER BY RAND() LIMIT 1)
    UNION (

        SELECT * FROM art WHERE price BETWEEN 100000 AND 200000 ORDER BY RAND() LIMIT 1
    )
    UNION (
        SELECT * FROM art WHERE price BETWEEN 200000 AND 500000 ORDER BY RAND() LIMIT 1

    )
    UNION (
        SELECT * FROM art WHERE price BETWEEN 500000 AND 1000000 ORDER BY RAND() LIMIT 1
    );

    COMMIT;

END $$

DELIMITER ;